version: '3'
services:
  api:
    image: node:12.18.4
    working_dir: /code
    ports:
      - '5000:5000'
    environment:  
      - PGUSER=journal-app
      - PGHOST=db
      - PGPASSWORD=journal-app-pass
      - PGDATABASE=journal-app-db
      - PGPORT=5432
    volumes: 
      - type: bind
        source: ./api
        target: /code
    command: bash -c "npm install && npm run seedDev && npm start"
    depends_on:
      - db

  db: 
    image: postgres:12.4
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_USER=journal-app
      - POSTGRES_DB=journal-app-db
      - POSTGRES_PASSWORD=journal-app-pass
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - "./db/migrations:/docker-entrypoint-initdb.d/:ro"
  
volumes:
  dbdata:

